### ISSUE TITLE
Immediate parent or child query

### ISSUE THREAD

**Issue by 50kudos** [florinpatrascu/closure_table#1]
To be able to query immediate parent or child, the simplest way is to add `depth` (or level or what is your preference) column to `tree_paths` table

`descendants/2` and `ancestors/2` will accept a new option called `depth` (or whatever that matches the new column).

Thanks for making this package, I am evaluating and would love to contribute, but it would be great to hear from author before introducing public data structure breaking change (e.g. change `paths` to list of map instead.)

**Comment by florinpatrascu** [comment]
Thank you for checking this project, and for the suggestion. I had in mind taking it further, and using `depth` for finding the immediate children (or parent), was a desired next iteration.

To stay in the spirit of the implementation, let's add a new column to the `tree_paths` table; the `depth` field, respectively. This way we let the db do what it does best :)

And yes, I would love a PR or any feedback that will help improving this lil' library - thank you!

**Comment by florinpatrascu** [comment]
Hi @50kudos - thanks again for the PR, which I merged a few minutes ago and I apologize for the lag, but am too busy with my day work. Wanted to ask, are you planning to refactor the memory adapter as well, in order to support the depth optional API? Thanks again!

**Comment by 50kudos** [comment]
Hi @florinpatrascu thanks for reviewing and merging. No need to apologize, I'm using your package now :). I have an idea for the memory adapter, it should be straightforward. In fact, the PR wasn't exposing depth as a 3rd element of tree_paths, but I'm still able to walk the tree. I'll look into memory adapter next week. Thanks!

**Comment by florinpatrascu** [comment]
> I'm using your package now :)

this is awesome, ty! BTW, it's ours now, haha. And I'd love to hear back from you how it performs over time. It works for me, but your mileage may vary. And thanks for looking into the memory adapter. I know it's a pita sometimes, to maintain the same behaviour for two different "backends" db and memory, but I made a self imposed rule not to force my users to use a db or an external service, during tests or development - more ergonomic for their dev workflow that way, but also more work for us, the maintainers. The memory adapter is meant for exactly this reason, and for situations where there is a need for a light tree structure, i.e. when its state is restored from a persistent medium, etc.
