### ISSUE TITLE
Ecto adapter fails to accept anything other than integers for IDs

### ISSUE THREAD

**Issue by beckler** [florinpatrascu/closure_table#13]
Was attempting to use this in a database that uses `:binary_id` as the primary ID type on all tables, but it immediately failed.

Mainly due to this line: https://github.com/florinpatrascu/closure_table/blob/main/lib/cte/adapter/ecto.ex#L309

This is the error thrown: 
```
** (Ecto.Query.CastError) deps/closure_table/lib/cte/adapter/ecto.ex:307: value `"f74992a5-2ec4-438c-bfc4-97a31c925d0f"` in `select` cannot be cast to type :integer in query:
```

**Comment by florinpatrascu** [comment]
Your observation is correct. We're not supporting other types of PKs, for now.

**Comment by florinpatrascu** [comment]
we'll add this feature in v2, but we're just starting

**Comment by florinpatrascu** [comment]
The latest version 2.0.5 lets you personalize your PKs — give it a shot!
