### ISSUE TITLE
use `distance` instead of `depth`

### ISSUE THREAD

**Issue by scottming** [florinpatrascu/closure_table#4]
`distance` is more make sense; that's meaning the distance between two nodes.

`depth` also means the tree depth.

**Comment by florinpatrascu** [comment]
should we have to change it, then: `path_length` would be more appropriate. Changing it without preparing a transition would introduce disruptive incompatibilities with the user's code.

**Comment by scottming** [comment]
yes，I agree with`path_length`.

And, another question: If I want to sort the subtree, should I add a `sorter_number` field to the nodes table? and which part code I should change?

**Comment by florinpatrascu** [comment]
~sorter_number~, probably not. I'd go with something that it's about the node's own `weight`, `position`, or something like that?!

> ... and which part code I should change?

Well, if you read the source more carefully, you'll see that you'd have to implement any new cross-cutting features, such as the one you suggest, in the both adapters; Ecto and Memory, respectively.

Keep in mind tho' some users of this library are already employing CT independent solutions for sorting the nodes, as in adding their own meta to the node definitions, and such ¯\\_(ツ)_/¯ HTH

**Comment by florinpatrascu** [comment]
Closing this. We can reopen as soon as there's a PR supporting the dialog in this thread.
